config/routes.rb
require 'sidekiq/web'

class ActionDispatch::Routing::Mapper
  def edit_step(name)
    resource name,
             only:       [:edit, :update],
             controller: name,
             path_names: { edit: '' }
  end

  def show_step(name)
    resource name,
             only:       [:show],
             controller: name
  end

  def collection_step(name, action)
    resources name, only: [] do
      get action, on: :collection
    end
  end

  def public_domain
    'https://appeal-tax-tribunal.service.gov.uk'.freeze
  end
end

Rails.application.routes.draw do
  # TODO: these redirections can be removed in the future, as it is to ensure
  # users accessing through the old domain are redirected to the new one
  #
  constraints host: 'tax-tribunal.service.dsd.io' do
    get '/' => redirect(public_domain, status: 301)
    match '*path.:format' => redirect("#{public_domain}/%{path}.%{format}", status: 301), via: :get
    match '*path' => redirect("#{public_domain}/%{path}", status: 301), via: :get
  end

  scope "/:locale", locale: /en|cy/ do
    devise_for :users,
               controllers: {
                 registrations: 'users/registrations',
                 passwords: 'users/passwords',
                 sessions: 'users/logins'
               },
               path_names: {
                 sign_in: 'login',
                 sign_out: 'logout'
               }

    namespace :steps do
      namespace :appeal do
        root 'case_type#edit'

        edit_step :case_type
        edit_step :case_type_show_more
        edit_step :dispute_type
        edit_step :penalty_amount
        edit_step :tax_amount
        edit_step :penalty_and_tax_amounts
        show_step :tax_credits_kickout
      end

      namespace :challenge do
        edit_step :decision
        edit_step :decision_status
        show_step :must_challenge_hmrc
        show_step :must_ask_for_review
        show_step :must_wait_for_challenge_decision
        show_step :must_wait_for_review_decision
      end

      namespace :hardship do
        edit_step :disputed_tax_paid
        edit_step :hardship_review_requested
        edit_step :hardship_review_status
        edit_step :hardship_reason
        edit_step :hardship_contact_hmrc
      end

      namespace :lateness do
        edit_step :in_time
        edit_step :lateness_reason
      end

      namespace :closure do
        root 'case_type#edit'

        edit_step :case_type
        edit_step :enquiry_details
        edit_step :additional_info
        edit_step :eu_exit
        edit_step :need_support
        edit_step :what_support
        edit_step :support_documents
        show_step :check_answers
        collection_step :check_answers, :resume
        show_step :confirmation
      end

      namespace :details do
        edit_step :taxpayer_type
        edit_step :taxpayer_details
        edit_step :send_taxpayer_copy
        edit_step :has_representative
        edit_step :representative_professional_status
        edit_step :representative_type
        edit_step :representative_details
        edit_step :send_representative_copy
        edit_step :grounds_for_appeal
        edit_step :outcome
        edit_step :need_support
        edit_step :letter_upload_type
        edit_step :letter_upload
        edit_step :documents_upload
        show_step :documents_upload_problems
        show_step :check_answers
        collection_step :check_answers, :resume
        show_step :confirmation
        edit_step :user_type
        edit_step :representative_approval
        edit_step :what_support
        edit_step :eu_exit
      end

      edit_step :save_and_return
      edit_step :select_language
    end

    namespace :users do
      devise_scope :user do
        get 'login/logged_out', to: 'logins#logged_out'
        delete 'login/restart_account_creation', to: 'logins#restart_account_creation'
        get 'password/reset_sent', to: 'passwords#reset_sent'
        get 'password/reset_confirmation', to: 'passwords#reset_confirmation'
        get 'registration/update_confirmation', to: 'registrations#update_confirmation'
        get 'registration/save_confirmation', to: 'registrations#save_confirmation'
        get 'login/save_confirmation', to: 'logins#save_confirmation'
      end

      resources :cases, only: [:index, :destroy, :edit, :update] do
        get :resume, on: :member
      end
    end


    delete '/session', to: 'sessions#destroy', as: 'session'

    scope 'uploader/:document_key' do
      resources :documents, only: [:create, :destroy]
    end

    resources :appeal_cases, :closure_cases, only: [:create]

    resource :errors, only: [] do
      get :invalid_session
      get :case_not_found
      get :case_submitted
      get :unhandled
      get :not_found
    end

    namespace :surveys do
      resource :feedback, only: [:new, :create], controller: :feedback do
        get :thanks
      end
    end
  end

  resource :session, only: [] do
    member do
      get :ping
      post :create_and_fill_appeal
      post :create_and_fill_appeal_and_lateness
      post :create_and_fill_appeal_and_lateness_and_appellant
    end
  end

  namespace :admin do
    resources :upload_problems_report, only: [:index]
    resources :other_case_types_report, only: [:index]
    resources :other_dispute_types_report, only: [:index]
    resources :glimr_generation, only: [:new, :create]
    resources :case_documents, only: [:show]
    get 'documents/*path', to: 'case_documents#tc'
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(
        username,
        ENV["ADMIN_USERNAME"]) &
        ActiveSupport::SecurityUtils.secure_compare(
          Digest::SHA256.hexdigest(password),
          ENV["ADMIN_PASSWORD"])
    end
    mount Sidekiq::Web => "/sidekiq"
  end

  scope module: 'tax_tribs' do
    resources :status, only: [:index]
  end

  root to: 'home#index'
  get '/:locale', to: 'home#index', as: :local_root
  get :start, to: redirect('/', status: 301)

  scope "/:locale", locale: /en|cy/, defaults: { locale: 'en'} do
    get :appeal, to: 'appeal_home#index'
    get :closure, to: 'closure_home#index'

    get :guidance, to: 'home#guidance'
    get :contact, to: 'home#contact', as: :contact_page
    get :cookies, to: 'home#cookies', as: :cookies_page
    put :cookies, to: 'home#update', as: :set_cookie_preference
    get 'terms-conditions', to: 'home#terms', as: :terms_page
    get 'privacy', to: 'home#privacy', as: :privacy_page
    get 'accessibility-statement', to: 'home#accessibility', as: :accessibility_page
  end

  get '/.well-known/acme-challenge/:id', to: 'ssl#auth'
  # catch-all route
  # :nocov:
  match '*path', to: 'errors#not_found', via: :all, constraints:
                                                      lambda { |_request| !Rails.application.config.consider_all_requests_local }
  # :nocov:
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    reset_tribunal_case_session
    @link_sections = link_sections
  end

  def contact
  end

  def cookies
    @form_object = Cookie::SettingForm.new(
      request:
    )
  end

  def terms
  end

  def privacy
  end

  def accessibility
  end

  def guidance
  end

  def update
    Cookie::SettingForm.new(
      cookie_setting:,
      response:
    ).save
    flash[:cookie_notification] = cookie_notification
    redirect_to request.referer
  end

  private

  def cookie_setting
    params[:cookie_setting_form]
      .permit(:cookie_setting)
      .to_h
      .fetch(:cookie_setting)
  end

  def cookie_notification
    if params[:cookie_banner].present?
      cookie_setting
    else
      true
    end
  end

  # [task name (used for i18n), estimated minutes to complete this task, path/url to the task]
  # Use '0' minutes to hide the time to complete paragraph
  def link_sections
    [
      [:appeal, 30, appeal_path(locale: I18n.locale)],
      [:close, 15, closure_path(locale: I18n.locale)],
      [:home_login, 0, helpers.login_or_portfolio_path],
      [:guidance, 0, guidance_path(locale: I18n.locale)]
    ]
  end
end

app/views/home/accessibility.html.erb
<% title t('.page_title') %>

<h1 class="govuk-heading-xl"><%=t '.heading_html' %></h1>

<%= t('.description_html',
      tax_tribunal_phone: Rails.configuration.tax_tribunal_phone) %>

app/views/home/contact.html.erb
<% title t('.page_title') %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">

    <h1 class="govuk-heading-l"><%=t '.heading' %></h1>

    <p class="govuk-body-l"><%=t '.lead_text' %></p>

    <%= t('.description_html',
          tax_tribunal_email: Rails.configuration.tax_tribunal_email,
          tax_tribunal_phone: Rails.configuration.tax_tribunal_phone) %>

  </div>
</div>

app/views/home/cookies.html.erb
<% title t('cookies.page_title') %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">

    <h1 class="govuk-heading-l"><%=t 'cookies.heading' %></h1>

    <p class="govuk-body-l"><%=t 'cookies.lead_text' %></p>


    <p class="govuk-body"><%= t 'cookies.intro.line_1' %></p>
    <ul class="govuk-list govuk-list--bullet">
      <li><%= t 'cookies.intro.line_2' %></li>
      <li><%= t 'cookies.intro.line_3' %></li>
    </ul>
    <p class="govuk-body"><%= t 'cookies.intro.line_4' %></p>
    <p class="govuk-body"><%= t 'cookies.intro.line_5' %></p>
    <h2 class="govuk-heading-s"><%= t 'cookies.section_list.further_information' %></h2>
    <p class="govuk-body"><%= t 'cookies.further_info.line_1_html' %></p>
    <p class="govuk-body"><%= t 'cookies.further_info.line_2_html' %></p>
    <h2 class="govuk-heading-m"><%= t 'cookies.section_list.how_we_use' %></h2>

    <p class="govuk-body"><strong><%= t 'cookies.how_we_use.essential_cookies' %></strong></p>
    <p class="govuk-body"><%= t 'cookies.how_we_use.line_1' %></p>

    <p class="govuk-body"><strong><%= t 'cookies.how_we_use.remembering_progress' %></strong></p>
    <p class="govuk-body"><%= t 'cookies.how_we_use.line_2' %></p>
    <table class="govuk-table">
      <thead class="govuk-table__head">
      <tr class="govuk-table__row">
        <th scope="col" class="govuk-table__header"><%= t 'cookies.how_we_use.table_2.header_1' %></th>
        <th scope="col" class="govuk-table__header"><%= t 'cookies.how_we_use.table_2.header_2' %></th>
        <th scope="col" class="govuk-table__header"><%= t 'cookies.how_we_use.table_2.header_3' %></th>
      </tr>
      </thead>
      <tbody>
      <tr class="govuk-table__row">
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_2.row_1.col_1' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_2.row_1.col_2' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_2.row_1.col_3' %></td>
      </tr>
      </tbody>
    </table>

    <p class="govuk-body"><strong><%= t 'cookies.how_we_use.cookies_message.header' %></strong></p>
    <p class="govuk-body"><%= t 'cookies.how_we_use.cookies_message.line1' %></p>
    <table class="govuk-table">
        <thead class="govuk-table__head">
            <tr class="govuk-table__row">
                <th scope="col" class="govuk-table__header"><%= t 'cookies.how_we_use.cookies_message.table.header_1' %></th>
                <th scope="col" class="govuk-table__header"><%= t 'cookies.how_we_use.cookies_message.table.header_2' %></th>
                <th scope="col" class="govuk-table__header"><%= t 'cookies.how_we_use.cookies_message.table.header_3' %></th>
            </tr>
        </thead>
        <tbody>
            <tr class="govuk-table__row">
                <td class="govuk-table__cell"><%= t 'cookies.how_we_use.cookies_message.table.col_1' %></td>
                <td class="govuk-table__cell"><%= t 'cookies.how_we_use.cookies_message.table.col_2' %></td>
                <td class="govuk-table__cell"><%= t 'cookies.how_we_use.cookies_message.table.col_3' %></td>
            </tr>
        </tbody>
    </table>


    <h2 class="govuk-heading-m"><%= t 'cookies.section_list.analytics_cookies' %></h2>
    <p class="govuk-body"><strong><%= t 'cookies.how_we_use.measuring_usage' %></strong></p>
    <p class="govuk-body"><%= t 'cookies.how_we_use.line_3_html' %></p>
    <p class="govuk-body"><%= t 'cookies.how_we_use.line_4' %></p>
    <ul class="govuk-list govuk-list--bullet">
      <li><%= t 'cookies.how_we_use.line_5' %></li>
      <li><%= t 'cookies.how_we_use.line_6' %></li>
      <li><%= t 'cookies.how_we_use.line_7' %></li>
      <li><%= t 'cookies.how_we_use.line_8' %></li>
    </ul>
    <p class="govuk-body"><%= t 'cookies.how_we_use.line_9' %></p>
    <p class="govuk-body"><%= t 'cookies.how_we_use.line_10' %></p>
    <p class="govuk-body"><%= t 'cookies.how_we_use.line_11' %></p>
    <p class="govuk-body"><%= t 'cookies.how_we_use.line_12' %></p>
    <table class="govuk-table">
      <thead class="govuk-table__head">
      <tr class="govuk-table__row">
        <th scope="col" class="govuk-table__header"><%= t 'cookies.how_we_use.table_3.header_1' %></th>
        <th scope="col" class="govuk-table__header"><%= t 'cookies.how_we_use.table_3.header_2' %></th>
        <th scope="col" class="govuk-table__header"><%= t 'cookies.how_we_use.table_3.header_3' %></th>
      </tr>
      </thead>
      <tbody>
      <tr class="govuk-table__row">
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_3.row_1.col_1' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_3.row_1.col_2' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_3.row_1.col_3' %></td>
      </tr>
      <tr class="govuk-table__row">
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_3.row_2.col_1' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_3.row_2.col_2' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_3.row_2.col_3' %></td>
      </tr>
      <tr class="govuk-table__row">
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_3.row_3.col_1' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_3.row_3.col_2' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_3.row_3.col_3' %></td>
      </tr>
      </tbody>
    </table>
    <p class="govuk-body"><%= t 'cookies.how_we_use.line_13' %></p>
    <table class="govuk-table">
      <thead class="govuk-table__head">
      <tr class="govuk-table__row">
        <th scope="col" class="govuk-table__header"><%= t 'cookies.how_we_use.table_4.header_1' %></th>
        <th scope="col" class="govuk-table__header"><%= t 'cookies.how_we_use.table_4.header_2' %></th>
        <th scope="col" class="govuk-table__header"><%= t 'cookies.how_we_use.table_4.header_3' %></th>
      </tr>
      </thead>
      <tbody>
      <tr class="govuk-table__row">
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_4.row_1.col_1' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_4.row_1.col_2' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_4.row_1.col_3' %></td>
      </tr>
      <tr class="govuk-table__row">
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_4.row_2.col_1' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_4.row_2.col_2' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_4.row_2.col_3' %></td>
      </tr>
      <tr class="govuk-table__row">
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_4.row_3.col_1' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_4.row_3.col_2' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_4.row_3.col_3' %></td>
      </tr>
      <tr class="govuk-table__row">
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_4.row_4.col_1' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_4.row_4.col_2' %></td>
        <td class="govuk-table__cell"><%= t 'cookies.how_we_use.table_4.row_4.col_3' %></td>
      </tr>
      </tbody>
    </table>
    <p class="govuk-body"><%= t 'cookies.how_we_use.line_14_html' %></p>


    <h2 id="cookie-settings" class="govuk-heading-m"><%= t 'cookies.section_list.accept_cookies' %></h2>
    <p class="govuk-body">
        <%= govuk_error_summary %>
        <%= step_form @form_object, html: { class: 'ga-radioButtonGroup'  } do |f| %>
            <%= f.govuk_collection_radio_buttons :cookie_setting,
             Cookie::SettingForm.choices, :to_s, nil,
             legend: { text: '', size: 'l' }
            %>

        <%= f.submit t('helpers.submit.cookie_setting'), class: 'govuk-button' %>
    <% end %>
    </p>

  </div>
</div>

app/views/home/dummy_start_page.html.erb
<div class="grid-row">
    <div class="column-two-thirds">

      <form class="js_route" action="/">

        <h1 class="heading-large">Appeal to the tax tribunal</h1>

        <p class="lede">The tax tribunal is run by the Ministry of Justice.</p>
        <p>Try and settle your dispute directly first. If you can't, a judge will make an impartial decision on your case.</p>
        <p>The tribunal is independent and uses the information you provide to hear things from your side.</p>
        <h2 class="heading-medium">You will need:</h2>
        <ul class="list list-bullet">
        <li><strong>a scan or photo</strong> of the original notice or review conclusion letter</li>
        <li><strong>reasons for your appeal</strong> to copy and paste or attach as a document</li>
        <li data-dependent="fees=yes" class="js-hidden"><strong>a way to pay your tribunal fee</strong> such as a debit or credit card, unless you are on a <a href="https://www.gov.uk/get-help-with-court-fees">low income or certain benefits</a></li>
        <li><strong><a href="https://drive.google.com/open?id=0B-4PgEZDV9SBczhkbGNDanJEa28">signed approval (PDF, 58Kb)</a></strong> if you want someone to represent you</li>
      </ul>

      <p class="notice util_mt-large">
        <i class="icon icon-important">
          <span class="visuallyhidden">Warning</span>
        </i>
        <strong class="bold-small">
          You can't save details so get everything ready before you start
        </strong>
      </p>

      <p>
        <input type="submit" class="button button-start" value="Start now">
      </p>
      <h2 class="heading-medium">Other ways to submit an appeal</h2>
      <ul class="list list-bullet">
        <li>You can use <a class="external" rel="external" href="http://hmctsformfinder.justice.gov.uk/HMCTS/GetForms.do?court_forms_category=Tax%20(First-tier%20Tribunal)">paper forms</a> to submit an appeal (T240) or close an enquiry (T245)</li>
        <li>
          Send your form by post to First-tier Tribunal (Tax Chamber), PO Box 16972, Birmingham, B16 6TZ
        </li>
      </ul>
      </form>

    </div>

    <div class="column-one-third">
      <aside class="govuk-related-items">

        <h2 class="heading-medium">Courts, sentencing and tribunals</h2>
        <nav role="navigation">
          <ul class="font-xsmall">
              <li><a href="https://www.gov.uk/court-fees-what-they-are">Court and tribunal fees</a></li>
              <li><a href="https://www.gov.uk/tax-tribunal">Guide to tax tribunals</a></li>
          </ul>
        </nav>

        <h2 class="heading-medium">Elsewhere on GOV.UK</h2>
        <nav role="navigation">
          <ul class="font-xsmall">
            <li><a href="https://www.gov.uk/tax-appeals">Disagree with a tax decision</a></li>
            <li><a href="https://www.gov.uk/government/publications/tax-chamber-tribunal-procedure-rules">Tax tribunal procedure rules</a></li>
          </ul>
        </nav>

      </aside>
    </div>
  </div>

app/views/home/guidance.html.erb
<% title t('guidance.page_title') %>
<% content_for(:back_link) do %>
  <%= link_to t('generic.back_link'), root_path, class: 'govuk-back-link' %>
<% end %>


<h1 class="govuk-heading-xl"><%=t 'guidance.heading' %></h1>

<p class="govuk-body-l"><%= t 'guidance.lead_text' %></p>

<h2 class="govuk-heading-l"><%= t 'guidance.subheading_1' %></h2>

<div class="govuk-accordion" data-module="govuk-accordion" id="accordion-1">
  <% t('guidance.accordion_1').each_with_index do |i, k|  %>
    <div class="govuk-accordion__section ">
      <div class="govuk-accordion__section-header">
        <h2 class="govuk-accordion__section-heading">
          <span class="govuk-accordion__section-button" id="<%="accordion-1-heading-#{k}"%>">
            <%= i[:question_html].html_safe %>
          </span>
        </h2>
      </div>
      <div id="<%="accordion-1-content-#{k}"%>" class="govuk-accordion__section-content" aria-labelledby="<%="accordion-1-heading-#{k}"%>">
        <%= i[:answer_html].html_safe %>
      </div>
    </div>
  <% end %>
</div>

<h2 class="govuk-heading-l"><%= t 'guidance.subheading_2' %></h2>

<%= t 'guidance.steps_details_html' %>

<div class="govuk-accordion" data-module="govuk-accordion" id="accordion-2">
  <% t('guidance.accordion_2').each_with_index do |i, k| %>
    <div class="govuk-accordion__section ">
      <div class="govuk-accordion__section-header">
        <h2 class="govuk-accordion__section-heading">
            <span class="govuk-accordion__section-button" id="<%="accordion-2-heading-#{k}"%>">
              <%= i[:question_html].html_safe %>
            </span>
        </h2>
      </div>
      <div id="<%="accordion-2-content-#{k}"%>" class="govuk-accordion__section-content" aria-labelledby="<%="accordion-2-heading-#{k}"%>">
        <%= i[:answer_html].html_safe % { approval_form_href: form_t239_link } %>
      </div>
    </div>
  <% end %>
</div>

<%= t 'guidance.feedback_html', feedback_url: 'https://www.smartsurvey.co.uk/s/TTFeed20/' %>

<p class="govuk-body" >
  <a class="govuk-link" href="#" onclick="window.print();return false;"><%= t('guidance.print') %></a>
</p>

app/views/home/index.html.erb
<% title '' %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l"><%= t '.heading' %></h1>

    <ul class="govuk-list task-list">
      <% @link_sections.each do |(name, minutes, path)| %>
          <li>
            <%= link_to t('.link_titles.%s' % name), path, class: 'task-link ga-pageLink govuk-link govuk-!-font-size-24', data: {ga_category: 'Type_app', ga_label: name} %>
            <%= content_tag(:p, t('.link_descriptions.%s' % name), class: 'govuk-!-font-size-24') %>
          </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/home/terms.html.erb
<% title t('terms.header') %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l"><%= t 'terms.header' %></h1>
    <span><%= t('terms.last_update').html_safe %></span>
    <p class="govuk-body"><cite><%= t('terms.info', privacy_link: link_to(t('terms.privacy'), privacy_page_path(locale: I18n.locale), class: "govuk-link")).html_safe %></cite></p>

    <ul class="govuk-list">
      <li><a href="#general" class="govuk-link" title=""><%= t 'terms.section_list.general' %></a></li>
      <li><a href="#applicable" class="govuk-link" title=""><%= t 'terms.section_list.applicable_law' %></a></li>
      <li><a href="#responsible" class="govuk-link" title=""><%= t 'terms.section_list.responsible' %></a></li>
      <li><a href="#gdpr" class="govuk-link" title=""><%= t 'terms.section_list.gdpr' %></a></li>
      <li><a href="#disclaimer" class="govuk-link" title=""><%= t 'terms.section_list.disclaimer' %></a></li>
    </ul>

    <h1 id="general" class="govuk-heading-l"><%= t 'terms.general.header' %></h1>
    <p class="govuk-body"><%= t 'terms.general.line_1' %></p>
    <p class="govuk-body"><%= t 'terms.general.line_2' %></p>
    <p class="govuk-body"><%= t 'terms.general.line_3' %></p>


    <h1 id="applicable" class="govuk-heading-l"><%= t 'terms.applicable_law.header' %></h1>
    <p class="govuk-body"><%= t 'terms.applicable_law.line_1' %></p>

    <ul class="standard-list">
      <li><%= t 'terms.applicable_law.list_1' %></li>
      <li><%= t 'terms.applicable_law.list_2' %></li>
      <li><%= t 'terms.applicable_law.list_3' %></li>
      <li><%= t 'terms.applicable_law.list_4' %></li>
    </ul>

    <h1 class="govuk-heading-l" id="responsible"><%= t 'terms.responsible.header' %></h1>

    <p class="govuk-body"><%= t 'terms.responsible.line_1' %></p>
    <p class="govuk-body"><%= t 'terms.responsible.line_2' %></p>
    <p class="govuk-body"><%= t 'terms.responsible.line_3' %></p>
    <p class="govuk-body"><%= t 'terms.responsible.line_4' %></p>


    <h1 class="govuk-heading-l" id="gdpr"><%= t 'terms.gdpr.header' %></h1>
    <p class="govuk-body"><%= t 'terms.gdpr.line_1' %></p>
    <p class="govuk-body"><%= t('terms.gdpr.line_2', privacy_link: link_to(t('terms.privacy'), privacy_page_path(locale: I18n.locale), class: "govuk-link")).html_safe %></p>
    <p class="govuk-body"><%= t 'terms.gdpr.line_3' %></p>
    <p class="govuk-body"><%= t 'terms.gdpr.line_4' %></p>

    <h1 class="govuk-heading-l" id="disclaimer"><%= t 'terms.disclaimer.header' %></h1>
    <p class="govuk-body"><%= t 'terms.disclaimer.line_1' %></p>
    <p class="govuk-body"><%= t 'terms.disclaimer.line_2' %></p>


  </div>
</div>